#!/bin/bash
# Scan MAC addresses in the background, dump into CSV file with prefix "log"

sudo rm /root/logs/log*
sleep 3
sudo /usr/sbin/airodump-ng -b bg -u 3 -w /root/logs/log --output-format csv wlan0mon &
